In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [3]:
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))

In [6]:
# Convert categorical data to numeric and separate target feature for training data

X_train=train_df.drop(columns = 'loan_status')
X_train=pd.get_dummies(X_train)

##separate target
target = ['loan_status']
y_train=train_df.loc[:,target].copy()

X_train.describe()

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,...,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N,debt_settlement_flag_Y
count,12180.000000,12180.000000,12180.000000,12180.000000,12180.000000,1.218000e+04,12180.000000,12180.000000,12180.000000,12180.000000,...,12180.000000,12180.0,12180.000000,12180.000000,12180.000000,12180.000000,12180.000000,12180.000000,12180.000000,12180.000000
mean,187893.694745,187893.694745,17399.579228,0.140899,509.150241,8.989320e+04,22.589516,0.256979,0.566502,12.680296,...,0.164039,1.0,0.083908,0.916092,0.853859,0.146141,0.971429,0.028571,0.999589,0.000411
std,99710.342179,99710.342179,10238.160884,0.052679,294.617726,1.684370e+05,23.903223,0.803027,0.814674,6.154663,...,0.370327,0.0,0.277261,0.277261,0.353262,0.353262,0.166605,0.166605,0.020258,0.020258
min,24.000000,24.000000,1000.000000,0.060000,30.890000,5.000000e+02,0.100000,0.000000,0.000000,2.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,104269.250000,104269.250000,10000.000000,0.103300,286.902500,5.000000e+04,14.500000,0.000000,0.000000,8.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000
50%,190128.000000,190128.000000,15000.000000,0.130800,438.530000,7.300000e+04,20.375000,0.000000,0.000000,11.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000
75%,274595.750000,274595.750000,25000.000000,0.177400,682.230000,1.035850e+05,27.290000,0.000000,1.000000,16.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000
max,355312.000000,355312.000000,40000.000000,0.308400,1671.880000,9.682505e+06,999.000000,15.000000,5.000000,65.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
X_train.columns

Index(['Unnamed: 0', 'index', 'loan_amnt', 'int_rate', 'installment',
       'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'open_acc',
       'pub_rec', 'revol_bal', 'total_acc', 'out_prncp', 'out_prncp_inv',
       'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'home_ownership_ANY',
       'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT',
       'verification_status_Not Verified',
       'verification_status_Source Verified', 'verification_status_Verified',
       'pymnt_plan_n', 'initial_list_status_f', 'initial_list_status_w',
       'application_type_Individual', 'application_type_Joint App',
       'hardship_flag_N', 'hardship_flag_Y', 'debt_settlement_flag_N',
       'debt_settlement_flag_Y'],
      dtype='object')

In [9]:
# Convert categorical data to numeric and separate target feature for testing data
X_test=test_df.drop(columns = 'loan_status')
X_test=pd.get_dummies(X_test)

##separate target
target = ['loan_status']
y_test=test_df.loc[:,target].copy()

X_test.describe()

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,...,verification_status_Source Verified,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N
count,4702.000000,4702.000000,4702.000000,4702.000000,4702.000000,4.702000e+03,4702.000000,4702.000000,4702.000000,4702.000000,...,4702.000000,4702.000000,4702.0,4702.000000,4702.000000,4702.000000,4702.000000,4702.000000,4702.000000,4702.0
mean,40848.125479,40848.125479,16983.889834,0.147490,503.512114,8.677217e+04,22.984243,0.205444,0.701616,12.709911,...,0.364738,0.113356,1.0,0.069120,0.930880,0.885793,0.114207,0.982773,0.017227,1.0
std,22099.925238,22099.925238,10122.727799,0.057906,293.240156,5.802277e+04,21.162972,0.634326,0.901247,6.046306,...,0.481408,0.317061,0.0,0.253684,0.253684,0.318096,0.318096,0.130129,0.130129,0.0
min,31.000000,31.000000,1000.000000,0.064600,31.140000,1.000000e+02,0.710000,0.000000,0.000000,2.000000,...,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
25%,22695.500000,22695.500000,9512.500000,0.103300,280.840000,5.200000e+04,14.920000,0.000000,0.000000,8.000000,...,0.000000,0.000000,1.0,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.0
50%,42024.500000,42024.500000,15000.000000,0.143000,443.960000,7.316650e+04,21.100000,0.000000,0.000000,12.000000,...,0.000000,0.000000,1.0,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.0
75%,60078.500000,60078.500000,24000.000000,0.186200,684.720000,1.050000e+05,27.980000,0.000000,1.000000,16.000000,...,1.000000,0.000000,1.0,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.0
max,77340.000000,77340.000000,40000.000000,0.288000,1604.180000,1.092000e+06,999.000000,8.000000,5.000000,53.000000,...,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0

In [10]:
X_test.columns

Index(['Unnamed: 0', 'index', 'loan_amnt', 'int_rate', 'installment',
       'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'open_acc',
       'pub_rec', 'revol_bal', 'total_acc', 'out_prncp', 'out_prncp_inv',
       'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'home_ownership_ANY',
       'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT',
       'verification_status_Not Verified',
       'verification_status_Source Verified', 'verification_status_Verified',
       'pymnt_plan_n', 'initial_list_status_f', 'initial_list_status_w',
       'application_type_Individual', 'application_type_Joint App',
       'hardship_flag_N', 'hardship_flag_Y', 'debt_settlement_flag_N'],
      dtype='object')

In [11]:
# add missing dummy variables to testing set

# Get missing columns in the training test
missing_cols = set( X_train.columns ) - set( X_test.columns )
# Add a missing column in test set with default value equal to 0
for c in missing_cols:
    X_test[c] = 0
# Ensure the order of column in the test set is in the same order than in train set
X_train, X_test = X_train.align(X_test, axis=1)

# Prediction:

### I think

In [ ]:
# Train the Logistic Regression model on the unscaled data and print the model score

In [ ]:
# Train a Random Forest Classifier model and print the model score

In [ ]:
# Scale the data

In [ ]:
# Train the Logistic Regression model on the scaled data and print the model score

In [ ]:
# Train a Random Forest Classifier model on the scaled data and print the model score